// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApp.Database;

namespace SchoolApp.Database.Migrations
{
    [DbContext(typeof(SchoolDatabase))]
    [Migration("20230420082636_AddTableStudentsMigration")]
    partial class AddTableStudentsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("SchoolApp.Database.Entities.SchoolClass", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("SchoolClasses");
            });

            modelBuilder.Entity("SchoolApp.Database.Entities.Student", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("SchoolClassId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Surname")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SchoolClassId");

                b.ToTable("Students");
            });

            modelBuilder.Entity("SchoolApp.Database.Entities.Student", b =>
            {
                b.HasOne("SchoolApp.Database.Entities.SchoolClass", "SchoolClass")
                    .WithMany()
                    .HasForeignKey("SchoolClassId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("SchoolClass");
            });
#pragma warning restore 612, 618
        }
    }
}